# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FProt-Client
version:      0.07
version_from: Client.pm
installdirs:  site
requires:
    Cwd:                           0
    File::Spec::Functions:         0
    File::stat:                    0
    File::Temp:                    0
    IO::Socket::INET:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
